// User
export const SET_CURRENT_USER = "SET_CURRENT_USER"

// Cart
export const CART_VIEW_TOGGLE_HIDDEN = "CART_VIEW_TOGGLE_HIDDEN"
export const ADD_CART_ITEM = "ADD_CART_ITEM"
export const REMOVE_CART_ITEM_FROM_CART = "REMOVE_CART_ITEM_FROM_CART"
export const REMOVE_SELECTED_CART_ITEM_FROM_CART = "REMOVE_SELECTED_CART_ITEM_FROM_CART"
export const REMOVE_CART_ITEMS_ON_SIGNOUT = "REMOVE_CART_ITEMS_ON_SIGNOUT"